spring:
  main:
    banner-mode: "off"
server:
  port: 8080

---
spring:
  profiles: development
server:
  port: 8081

---
spring:
  profiles: production
  main:
    banner-mode: "off"
server:
  port: 80